#!/bin/zsh

mackup backup

source ./brew-list-backup

brew list > ../Other/brew-list.backup

cd ~/git-repository/myBackup

git pull origin master
git add --all
git commit -m "normal sync"
git push origin master

