#!/bin/zsh

mackup backup

cd ~/git-repository/myBackup/shell/
source ./brew-list-backup

brew list > ../Other/brew-list.backup

cd ~/git-repository/myBackup

git status
git pull origin master
git add --all
git commit -m "normal sync"
git push origin master

