#!/bin/zsh

cd ~/git-repository/Note/buyitem/

/usr/bin/python ./main.py

cd ~/git-repository/Note/

git status
git pull origin master
git add --all
git commit -m "normal sync"
git push origin master
