#!/bin/zsh

source ~/git-repository/myBackup/shell/echoRed

echoRed 'BACKING UP myBackup...'

source ~/git-repository/myBackup/shell/myBackup-git-backup

print ''
echoRed 'BACKING UP Note...'
source ~/git-repository/myBackup/shell/note-git-backup

print ''
echoRed 'CHECK BREW OUTDATED...'
brew outdated

print ''
echoRed '--------------'
echoRed 'Finished.'
