#!/bin/zsh

echo -e '\033[31mBACKING UP CONFIGURATION...\033[0m'
mackup backup
cd ~/git-repository/myBackup
git add --all
git commit -a -m "normal sync"
git push origin master


echo -e '\033[31m'
echo 'BACKING UP GIT-REPOSITORY...'
echo -e '\033[0m'
cd ~/git-repository/Note
git add --all
git commit -a -m 'normal sync'
git push origin master


echo -e '\033[31mCHECK BREW OUTDATED...\033[0m'
brew outdated

print ''
echo -e '\033[31m--------------\033[0m'
echo -e '\033[31mFinished.\033[0m'
